spring.datasource.url=jdbc:postgresql://localhost:5432/edu-crm
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.application.name=edu-crm



## security token configuration
jwt.secret=YmFzZTY0LWVuY29kZWQtc2VjcmV0LWtleS1mb3ItdXNl
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000

## enable Bean Definition Overriding
spring.main.allow-bean-definition-overriding=true

## email

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

##redis
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sardorkucell@gmail.com
spring.mail.password=cuhnolflteimeuih
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
